import cgi, cgitb
cgitb.enable()
form = cgi.FieldStorage()
nm=form.getvalue('name')
f=form.getvalue('faculty')
b=form.getvalue('batch')
text = form.getvalue('about')
print ("Content-type:text/html\r\n\r\n")
print("")
print("")
print("")
print("")
print("")
print ("Data received from client form(s)")
print("Name: {}".format(nm))
print ("")
print("F Ting: {}".format(f))
print ("")
print("B Ting: {}".format(b))
print ("")
print("Text : {}".format(text))
print ("")
print("")
print ("")